### ISSUE TITLE
Code surrounded by if(true) is lost

### ISSUE THREAD

**Issue by cal101** [walkmod/walkmod-pmd-plugin#3]
```
-            if (true) {
-                System.out.println("hello");
-            }
```

**Comment by rpau** [comment]
Thanks 👍

**Comment by rpau** [comment]
I have written a test in this plugin and works. So, It is something regarding the phase where walkmod defines the minimum set of changes to write. I keep working on it

**Comment by cal101** [comment]
I simplified the case. The original has much more code inside.
If you get stuck I can redo the test and try to produce a real single test case.
I just wanted to avoid the seemingly unnessasary work ;-)

**Comment by rpau** [comment]
Issue fixed at 9d56f0654ea3bebed5ecebae2343e13a239db678

**Comment by cal101** [comment]
Line handling is a bid weird.

```
if (true) {
   1
   2
}

3
```
becomes
```
   1

2
3
```

**Comment by cal101** [comment]
Not completely fixed:

```
     @Override
     public EpsData create(InputStream in, ParsingState cur) throws IOException, IllegalFileException {
-        if(true) {
-            throw new UncheckedSystemException("not implemented");
-        }
         return null;
     }
```

If the "if" is to be removed so is the "return null" then.
False positives of pmd may be a problem here.
